// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Planejamento_Dietas_Refeicoes.Models;

#nullable disable

namespace Sistema_Planejamento_Dietas_Refeicoes.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251019151625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriasPorPorcao")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Refeicao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataRefeicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Refeicoes");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.RefeicaoAlimento", b =>
                {
                    b.Property<int>("RefeicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantidade")
                        .HasColumnType("REAL");

                    b.HasKey("RefeicaoId", "AlimentoId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("RefeicaoAlimentos");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Refeicao", b =>
                {
                    b.HasOne("Sistema_Planejamento_Dietas_Refeicoes.Models.Usuario", "usuario")
                        .WithMany("Refeicoes")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.RefeicaoAlimento", b =>
                {
                    b.HasOne("Sistema_Planejamento_Dietas_Refeicoes.Models.Alimento", "Alimento")
                        .WithMany("RefeicaoAlimentos")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Planejamento_Dietas_Refeicoes.Models.Refeicao", "Refeicao")
                        .WithMany("RefeicaoAlimentos")
                        .HasForeignKey("RefeicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Refeicao");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Alimento", b =>
                {
                    b.Navigation("RefeicaoAlimentos");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Refeicao", b =>
                {
                    b.Navigation("RefeicaoAlimentos");
                });

            modelBuilder.Entity("Sistema_Planejamento_Dietas_Refeicoes.Models.Usuario", b =>
                {
                    b.Navigation("Refeicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
