### requisição para raiz 
GET http://localhost:5123

### CRIAR USUÁRIO
POST http://localhost:5123/usuarios
Content-Type: application/json

{
    "Nome": "Maria",
    "Email": "maria@gmail.com",
    "Altura": 1.65,
    "Peso": 65.0,
    "Objetivo": "Emagrecimento"
}
### listar usuários
GET http://localhost:5123/usuarios

### ATUALIZAR USUÁRIO
PUT http://localhost:5123/usuarios/3
Content-Type: application/json

{
    "Nome": "Maria Silva",
    "Email": "maria.silva@example.com",
    "Altura": 1.70,
    "Peso": 80.0,
    "Objetivo": "Emagrecimento"
}
### EXCLUIR USUÁRIO
DELETE http://localhost:5123/usuarios/4

################################################
#                 ALIMENTOS                    #
################################################

### LISTAR ALIMENTOS
GET http://localhost:5123/alimentos 

### CRIAR ALIMENTO
POST http://localhost:5123/alimentos
Content-Type: application/json

{
    "Nome": "Feijoada",
    "Tipo": "Proteína",
    "Unidade": "g",
    "CaloriasPorPorcao": 150
}

### BUSCAR ALIMENTO POR ID
GET http://localhost:5123/alimentos/2

### ATUALIZAR ALIMENTO
PUT http://localhost:5123/alimentos/418
Content-Type: application/json

{
    "Nome": "Feijão Preto",
    "Tipo": "Proteína",
    "Unidade": "g",
    "CaloriasPorPorcao": 160
}

### EXCLUIR ALIMENTO
DELETE http://localhost:5123/alimentos/418

################################################
#
# REFEIÇÕES
#
################################################

### CRIAR UMA NOVA REFEIÇÃO
# @name CRIAR_REFEICAO
POST http://localhost:5123/refeicoes
Content-Type: application/json

{
  "usuarioId": 3,
  "nome": "Almoço",
  "descricao": "Testando a criação de refeições com seus alimentos.",
  "dataRefeicao": "2025-10-21T12:30:00",
  "refeicaoAlimentos": [
    {
      "alimentoId": 87,
      "quantidade": 150
    },
    {
      "alimentoId": 122,
      "quantidade": 100
    }
  ]
}

### LISTAR TODAS AS REFEIÇÕES DO USUÁRIO 3
GET http://localhost:5123/usuarios/3/refeicoes

### BUSCAR A REFEIÇÃO CRIADA POR ID
# A variável @refeicaoId é preenchida automaticamente com o ID da refeição criada acima
@refeicaoId = {{CRIAR_REFEICAO.response.body.id}}
GET http://localhost:5123/refeicoes/4


### DELETAR A REFEIÇÃO CRIADA
DELETE http://localhost:5123/refeicoes/6


### TENTAR CRIAR UMA REFEIÇÃO PARA UM USUÁRIO INEXISTENTE (Cenário de Erro)
POST http://localhost:5123/refeicoes
Content-Type: application/json

{
  "usuarioId": 999,
  "nome": "Refeição Fantasma",
  "descricao": "Isso deve falhar.",
  "dataRefeicao": "2025-10-19T13:00:00",
  "refeicaoAlimentos": [
    {
      "alimentoId": 10,
      "quantidade": 100
    }
  ]
}

### CALCULAR TOTAL DE CALORIAS DA REFEIÇÃO CRIADA
GET http://localhost:5123/refeicoes/5/total-calorias

### RELATÓRIO DIÁRIO DE CALORIAS PARA O USUÁRIO 3
# (Assumindo que a refeição criada anteriormente foi no dia 2025-10-19)
GET http://localhost:5123/usuarios/3/relatorio/diario?data=2025-10-21

### RELATÓRIO SEMANAL DE CALORIAS PARA O USUÁRIO 1
# (Calcula o total dos 7 dias terminando em 2025-10-19)
GET http://localhost:5123/usuarios/3/relatorio/semanal?dataFinal=2025-10-25

### LISTAR PELO TIPO DA REFEIÇÃO
GET http://localhost:5123/usuarios/3/alimentos?tipo=almoço